/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalalgoritmos;

import clases.*;
import com.lowagie.text.Font;
import com.lowagie.text.Paragraph;
import com.opencsv.CSVReader;
import com.opencsv.exceptions.CsvException;
import java.awt.Color;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;


public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Nodo[] resultados = null;
    
    int ID = 1; 
    ArbolBinario licencias = new ArbolBinario();
    ArbolReportes arbolReporte = new ArbolReportes();
    ArbolReportes arbolPadre = new ArbolReportes();
    
    public Principal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        loginBtn4 = new javax.swing.JPanel();
        bt_reporte = new javax.swing.JLabel();
        loginBtn7 = new javax.swing.JPanel();
        bt_importar = new javax.swing.JLabel();
        loginBtn8 = new javax.swing.JPanel();
        bt_buscar = new javax.swing.JLabel();
        loginBtn9 = new javax.swing.JPanel();
        bt_agregar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        P1 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        P2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLicencias = new javax.swing.JTable();
        jLabel30 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        N1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        N2 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        loginBtn10 = new javax.swing.JPanel();
        bt_importar1 = new javax.swing.JLabel();
        N3 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        ructxtbuscar = new javax.swing.JTextField();
        girotxtbuscar = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        areatxtbuscar = new javax.swing.JTextField();
        lictxtbuscar = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        buscarButton1 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        N4 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        Exit3 = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        txtTipoAgregar = new javax.swing.JTextField();
        txtAreaAgregar = new javax.swing.JTextField();
        txtGiroAgregar = new javax.swing.JTextField();
        txtRucAgregar = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        N5 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        txtRUCRep = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        TXTGiroRep = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        Exit4 = new javax.swing.JButton();
        filtros = new javax.swing.JButton();
        btnPadre = new javax.swing.JButton();
        txtTipoLic = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(25, 12, 1));

        loginBtn4.setBackground(new java.awt.Color(0, 0, 0));

        bt_reporte.setBackground(new java.awt.Color(204, 204, 0));
        bt_reporte.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        bt_reporte.setForeground(new java.awt.Color(255, 255, 255));
        bt_reporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carpeta.png"))); // NOI18N
        bt_reporte.setText("Reporte");
        bt_reporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_reporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_reporteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_reporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_reporteMouseExited(evt);
            }
        });

        javax.swing.GroupLayout loginBtn4Layout = new javax.swing.GroupLayout(loginBtn4);
        loginBtn4.setLayout(loginBtn4Layout);
        loginBtn4Layout.setHorizontalGroup(
            loginBtn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginBtn4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        loginBtn4Layout.setVerticalGroup(
            loginBtn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginBtn4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bt_reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        loginBtn7.setBackground(new java.awt.Color(0, 0, 0));

        bt_importar.setBackground(new java.awt.Color(204, 204, 0));
        bt_importar.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        bt_importar.setForeground(new java.awt.Color(255, 255, 255));
        bt_importar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_importar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/importacion-de-archivos.png"))); // NOI18N
        bt_importar.setText("Importar");
        bt_importar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_importar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_importarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_importarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_importarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout loginBtn7Layout = new javax.swing.GroupLayout(loginBtn7);
        loginBtn7.setLayout(loginBtn7Layout);
        loginBtn7Layout.setHorizontalGroup(
            loginBtn7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginBtn7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_importar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        loginBtn7Layout.setVerticalGroup(
            loginBtn7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginBtn7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bt_importar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        loginBtn8.setBackground(new java.awt.Color(0, 0, 0));

        bt_buscar.setBackground(new java.awt.Color(204, 204, 0));
        bt_buscar.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        bt_buscar.setForeground(new java.awt.Color(255, 255, 255));
        bt_buscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/archivo.png"))); // NOI18N
        bt_buscar.setText("Buscar");
        bt_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_buscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_buscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_buscarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout loginBtn8Layout = new javax.swing.GroupLayout(loginBtn8);
        loginBtn8.setLayout(loginBtn8Layout);
        loginBtn8Layout.setHorizontalGroup(
            loginBtn8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginBtn8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginBtn8Layout.setVerticalGroup(
            loginBtn8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginBtn8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        loginBtn9.setBackground(new java.awt.Color(0, 0, 0));

        bt_agregar.setBackground(new java.awt.Color(204, 204, 0));
        bt_agregar.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        bt_agregar.setForeground(new java.awt.Color(255, 255, 255));
        bt_agregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mas.png"))); // NOI18N
        bt_agregar.setText("Agregar");
        bt_agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_agregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_agregarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout loginBtn9Layout = new javax.swing.GroupLayout(loginBtn9);
        loginBtn9.setLayout(loginBtn9Layout);
        loginBtn9Layout.setHorizontalGroup(
            loginBtn9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginBtn9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginBtn9Layout.setVerticalGroup(
            loginBtn9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginBtn9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bt_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Usuario:");

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Nombre");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(193, 193, 193)
                .addComponent(loginBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126)
                .addComponent(loginBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(loginBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addComponent(loginBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel25))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(loginBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(loginBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(loginBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(loginBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1560, 90));

        P1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_menu4.png"))); // NOI18N

        jLabel27.setBackground(new java.awt.Color(102, 102, 102));
        jLabel27.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("¡Bienvenido al Sistema de ");

        javax.swing.GroupLayout P1Layout = new javax.swing.GroupLayout(P1);
        P1.setLayout(P1Layout);
        P1Layout.setHorizontalGroup(
            P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1Layout.createSequentialGroup()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 1036, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(P1Layout.createSequentialGroup()
                    .addGap(506, 506, 506)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(154, Short.MAX_VALUE)))
        );
        P1Layout.setVerticalGroup(
            P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1Layout.createSequentialGroup()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 769, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(P1Layout.createSequentialGroup()
                    .addGap(477, 477, 477)
                    .addComponent(jLabel27)
                    .addContainerGap(261, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab1", P1);

        P2.setBackground(new java.awt.Color(0, 0, 0));

        tblLicencias.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tblLicencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RUC", "GIRO", "ÁREA", "TIPO LICENCIA"
            }
        ));
        jScrollPane1.setViewportView(tblLicencias);

        jLabel30.setBackground(new java.awt.Color(102, 102, 102));
        jLabel30.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Licencias de la Municipalidad");

        javax.swing.GroupLayout P2Layout = new javax.swing.GroupLayout(P2);
        P2.setLayout(P2Layout);
        P2Layout.setHorizontalGroup(
            P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P2Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P2Layout.createSequentialGroup()
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(353, 353, 353))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
        P2Layout.setVerticalGroup(
            P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", P2);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1030, 810));

        N1.setBackground(new java.awt.Color(34, 19, 6));

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("¡Bienvenido al Sistema de ");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Licencias de la Municipalidad!");

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("¿Cómo Utilizar el Sistema?");

        jLabel12.setBackground(new java.awt.Color(102, 102, 102));
        jLabel12.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Importar Datos:");

        jLabel13.setBackground(new java.awt.Color(102, 102, 102));
        jLabel13.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Comienza importando tus datos existentes a través");

        jLabel14.setBackground(new java.awt.Color(102, 102, 102));
        jLabel14.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("de la opción de importación de CSV. Asegúrate de que tu");

        jLabel15.setBackground(new java.awt.Color(102, 102, 102));
        jLabel15.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("sin problemas.");

        jLabel16.setBackground(new java.awt.Color(102, 102, 102));
        jLabel16.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("archivo siga el formato adecuado para una importación");

        jLabel17.setBackground(new java.awt.Color(102, 102, 102));
        jLabel17.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Buscar Información:");

        jLabel18.setBackground(new java.awt.Color(102, 102, 102));
        jLabel18.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Usa la búsqueda para acceder a registros específicos.");

        jLabel19.setBackground(new java.awt.Color(102, 102, 102));
        jLabel19.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Agregar Licencias:");

        jLabel20.setBackground(new java.awt.Color(102, 102, 102));
        jLabel20.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Registra nuevas licencias fácilmente mediante el formulario");

        jLabel21.setBackground(new java.awt.Color(102, 102, 102));
        jLabel21.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("de agregación.");

        jLabel22.setBackground(new java.awt.Color(102, 102, 102));
        jLabel22.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Generar Reportes:");

        jLabel23.setBackground(new java.awt.Color(102, 102, 102));
        jLabel23.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Mantén un control detallado y actualiza tu información");

        jLabel24.setBackground(new java.awt.Color(102, 102, 102));
        jLabel24.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("generando reportes periódicos.");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gato.png"))); // NOI18N

        javax.swing.GroupLayout N1Layout = new javax.swing.GroupLayout(N1);
        N1.setLayout(N1Layout);
        N1Layout.setHorizontalGroup(
            N1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N1Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(N1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, N1Layout.createSequentialGroup()
                        .addGroup(N1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(N1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, N1Layout.createSequentialGroup()
                        .addGroup(N1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        N1Layout.setVerticalGroup(
            N1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(38, 38, 38)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addGap(35, 35, 35)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addGap(27, 27, 27)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab2", N1);

        N2.setBackground(new java.awt.Color(34, 19, 6));

        jLabel29.setBackground(new java.awt.Color(102, 102, 102));
        jLabel29.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Importar Archivo CSV");

        jLabel32.setBackground(new java.awt.Color(102, 102, 102));
        jLabel32.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Utiliza este botón para importar archivos CSV con datos de");

        jLabel33.setBackground(new java.awt.Color(102, 102, 102));
        jLabel33.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("de información de manera rápida y precisa.");

        jLabel34.setBackground(new java.awt.Color(102, 102, 102));
        jLabel34.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("licencias. Esta función te permite cargar grandes volúmenes");

        loginBtn10.setBackground(new java.awt.Color(0, 0, 0));

        bt_importar1.setBackground(new java.awt.Color(204, 204, 0));
        bt_importar1.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        bt_importar1.setForeground(new java.awt.Color(255, 255, 255));
        bt_importar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_importar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/importacion-de-archivos.png"))); // NOI18N
        bt_importar1.setText("Importar");
        bt_importar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bt_importar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_importar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_importar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_importar1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout loginBtn10Layout = new javax.swing.GroupLayout(loginBtn10);
        loginBtn10.setLayout(loginBtn10Layout);
        loginBtn10Layout.setHorizontalGroup(
            loginBtn10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginBtn10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_importar1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginBtn10Layout.setVerticalGroup(
            loginBtn10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginBtn10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bt_importar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout N2Layout = new javax.swing.GroupLayout(N2);
        N2.setLayout(N2Layout);
        N2Layout.setHorizontalGroup(
            N2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, N2Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(N2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(N2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, N2Layout.createSequentialGroup()
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(116, 116, 116))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, N2Layout.createSequentialGroup()
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(66, 66, 66))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, N2Layout.createSequentialGroup()
                            .addComponent(loginBtn10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(192, 192, 192)))))
        );
        N2Layout.setVerticalGroup(
            N2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel29)
                .addGap(63, 63, 63)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel33)
                .addGap(323, 323, 323)
                .addComponent(loginBtn10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab1", N2);

        N3.setBackground(new java.awt.Color(34, 19, 6));

        jLabel37.setFont(new java.awt.Font("Poppins Medium", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ruc.png"))); // NOI18N
        jLabel37.setText("  RUC del establecimiento");

        ructxtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ructxtbuscarActionPerformed(evt);
            }
        });
        ructxtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ructxtbuscarKeyReleased(evt);
            }
        });

        girotxtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girotxtbuscarActionPerformed(evt);
            }
        });
        girotxtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                girotxtbuscarKeyReleased(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Poppins Medium", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fabrica.png"))); // NOI18N
        jLabel38.setText("  Giro de Actividad");

        jLabel39.setFont(new java.awt.Font("Poppins Medium", 1, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/biblioteca.png"))); // NOI18N
        jLabel39.setText("  Área del establecimiento ");

        areatxtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areatxtbuscarActionPerformed(evt);
            }
        });
        areatxtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                areatxtbuscarKeyReleased(evt);
            }
        });

        lictxtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lictxtbuscarActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Poppins Medium", 1, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/certificado.png"))); // NOI18N
        jLabel40.setText("  Tipo de licencia");

        buscarButton1.setBackground(new java.awt.Color(0, 0, 0));
        buscarButton1.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        buscarButton1.setForeground(new java.awt.Color(255, 255, 255));
        buscarButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/archivo.png"))); // NOI18N
        buscarButton1.setText("Buscar");
        buscarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButton1ActionPerformed(evt);
            }
        });

        jLabel28.setBackground(new java.awt.Color(102, 102, 102));
        jLabel28.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Buscar Licencias:");

        jLabel31.setBackground(new java.awt.Color(102, 102, 102));
        jLabel31.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Encuentra rápidamente la información que necesitas utilizando nuestra");

        jLabel35.setBackground(new java.awt.Color(102, 102, 102));
        jLabel35.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText(" licencia, nombre del titular, tipo de licencia, y más.");

        jLabel36.setBackground(new java.awt.Color(102, 102, 102));
        jLabel36.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("herramienta de búsqueda avanzada. Puedes buscar por número de");

        javax.swing.GroupLayout N3Layout = new javax.swing.GroupLayout(N3);
        N3.setLayout(N3Layout);
        N3Layout.setHorizontalGroup(
            N3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N3Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(N3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(N3Layout.createSequentialGroup()
                        .addGroup(N3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(N3Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(119, 119, 119))
                    .addGroup(N3Layout.createSequentialGroup()
                        .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(N3Layout.createSequentialGroup()
                        .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(N3Layout.createSequentialGroup()
                .addGroup(N3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, N3Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(areatxtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(N3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(N3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buscarButton1)
                            .addComponent(lictxtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(N3Layout.createSequentialGroup()
                .addGroup(N3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(N3Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addGroup(N3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel38)
                            .addComponent(girotxtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ructxtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(N3Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addGroup(N3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39)
                            .addComponent(jLabel37)))
                    .addGroup(N3Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel40)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        N3Layout.setVerticalGroup(
            N3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel28)
                .addGap(33, 33, 33)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35)
                .addGap(30, 30, 30)
                .addComponent(jLabel37)
                .addGap(29, 29, 29)
                .addComponent(ructxtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel38)
                .addGap(27, 27, 27)
                .addComponent(girotxtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel39)
                .addGap(24, 24, 24)
                .addComponent(areatxtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel40)
                .addGap(18, 18, 18)
                .addComponent(lictxtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buscarButton1)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab3", N3);

        N4.setBackground(new java.awt.Color(34, 19, 6));

        jLabel42.setFont(new java.awt.Font("Poppins Medium", 1, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ruc.png"))); // NOI18N
        jLabel42.setText("  RUC del establecimiento");

        jLabel43.setFont(new java.awt.Font("Poppins Medium", 1, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fabrica.png"))); // NOI18N
        jLabel43.setText("  Giro de Actividad");

        jLabel44.setFont(new java.awt.Font("Poppins Medium", 1, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/biblioteca.png"))); // NOI18N
        jLabel44.setText("  Área del establecimiento ");

        jLabel45.setFont(new java.awt.Font("Poppins Medium", 1, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/certificado.png"))); // NOI18N
        jLabel45.setText("  Tipo de licencia");

        Exit3.setBackground(new java.awt.Color(255, 255, 255));
        Exit3.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        Exit3.setForeground(new java.awt.Color(255, 51, 255));
        Exit3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mas.png"))); // NOI18N
        Exit3.setText("Nuevo");
        Exit3.setBorder(null);
        Exit3.setBorderPainted(false);
        Exit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit3ActionPerformed(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregar.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 51, 255));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mas.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(null);
        btnAgregar.setBorderPainted(false);
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        txtRucAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRucAgregarActionPerformed(evt);
            }
        });

        jLabel47.setBackground(new java.awt.Color(102, 102, 102));
        jLabel47.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Agregar Nueva Licencia:");

        jLabel48.setBackground(new java.awt.Color(102, 102, 102));
        jLabel48.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Añade nuevas licencias al sistema de manera sencilla. Completa");

        jLabel49.setBackground(new java.awt.Color(102, 102, 102));
        jLabel49.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("los campos requeridos y registra nuevas licencias en pocos pasos.");

        javax.swing.GroupLayout N4Layout = new javax.swing.GroupLayout(N4);
        N4.setLayout(N4Layout);
        N4Layout.setHorizontalGroup(
            N4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N4Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(N4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, N4Layout.createSequentialGroup()
                        .addGroup(N4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(N4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(N4Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(N4Layout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(N4Layout.createSequentialGroup()
                                    .addGap(100, 100, 100)
                                    .addGroup(N4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel44)
                                        .addGroup(N4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, N4Layout.createSequentialGroup()
                                                .addComponent(jLabel42)
                                                .addGap(6, 6, 6))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, N4Layout.createSequentialGroup()
                                                .addComponent(jLabel43)
                                                .addGap(31, 31, 31)))))))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, N4Layout.createSequentialGroup()
                        .addGroup(N4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtGiroAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRucAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(197, 197, 197))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, N4Layout.createSequentialGroup()
                        .addGroup(N4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel45)
                            .addComponent(txtAreaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTipoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(191, 191, 191))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, N4Layout.createSequentialGroup()
                        .addComponent(Exit3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))))
        );
        N4Layout.setVerticalGroup(
            N4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel47)
                .addGap(30, 30, 30)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel49)
                .addGap(55, 55, 55)
                .addComponent(jLabel42)
                .addGap(18, 18, 18)
                .addComponent(txtRucAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel43)
                .addGap(18, 18, 18)
                .addComponent(txtGiroAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel44)
                .addGap(18, 18, 18)
                .addComponent(txtAreaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel45)
                .addGap(18, 18, 18)
                .addComponent(txtTipoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(N4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Exit3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab4", N4);

        N5.setBackground(new java.awt.Color(34, 19, 6));

        jLabel51.setBackground(new java.awt.Color(102, 102, 102));
        jLabel51.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Generar Reporte:");

        jLabel52.setBackground(new java.awt.Color(102, 102, 102));
        jLabel52.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText(" Crea informes detallados sobre las licencias registradas.");

        jLabel53.setBackground(new java.awt.Color(102, 102, 102));
        jLabel53.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText(" según tus necesidades.");

        jLabel54.setBackground(new java.awt.Color(102, 102, 102));
        jLabel54.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Esta herramienta te permite generar reportes personalizados");

        jLabel55.setFont(new java.awt.Font("Poppins Medium", 1, 12)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ruc.png"))); // NOI18N
        jLabel55.setText("  RUC del establecimiento");

        txtRUCRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRUCRepActionPerformed(evt);
            }
        });

        jLabel56.setFont(new java.awt.Font("Poppins Medium", 1, 12)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fabrica.png"))); // NOI18N
        jLabel56.setText("  Giro de Actividad");

        jLabel57.setFont(new java.awt.Font("Poppins Medium", 1, 12)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/certificado.png"))); // NOI18N
        jLabel57.setText("  Tipo de licencia");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        Exit4.setBackground(new java.awt.Color(255, 255, 255));
        Exit4.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        Exit4.setForeground(new java.awt.Color(255, 51, 255));
        Exit4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/marque-el-circulo.png"))); // NOI18N
        Exit4.setText("Generar");
        Exit4.setBorder(null);
        Exit4.setBorderPainted(false);
        Exit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit4ActionPerformed(evt);
            }
        });

        filtros.setText("Eliminar Filtros");
        filtros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrosActionPerformed(evt);
            }
        });

        btnPadre.setText("Reporte General");
        btnPadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPadreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout N5Layout = new javax.swing.GroupLayout(N5);
        N5.setLayout(N5Layout);
        N5Layout.setHorizontalGroup(
            N5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, N5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(N5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, N5Layout.createSequentialGroup()
                        .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, N5Layout.createSequentialGroup()
                        .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, N5Layout.createSequentialGroup()
                        .addComponent(Exit4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(198, 198, 198))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, N5Layout.createSequentialGroup()
                        .addGroup(N5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(N5Layout.createSequentialGroup()
                                .addGroup(N5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtRUCRep, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel55)
                                    .addComponent(TXTGiroRep, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(N5Layout.createSequentialGroup()
                                        .addComponent(btnLimpiar)
                                        .addGap(46, 46, 46)
                                        .addComponent(btnBuscar)))
                                .addGap(27, 27, 27)
                                .addGroup(N5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(filtros)
                                    .addComponent(btnPadre))
                                .addGap(12, 12, 12))
                            .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59))))
            .addGroup(N5Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(N5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTipoLic, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel57)
                    .addComponent(jLabel56))
                .addGap(204, 204, 204))
        );
        N5Layout.setVerticalGroup(
            N5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel51)
                .addGap(36, 36, 36)
                .addComponent(jLabel52)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel54)
                .addGap(18, 18, 18)
                .addComponent(jLabel53)
                .addGap(52, 52, 52)
                .addComponent(jLabel55)
                .addGap(18, 18, 18)
                .addComponent(txtRUCRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel56)
                .addGap(26, 26, 26)
                .addComponent(TXTGiroRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel57)
                .addGroup(N5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(N5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtTipoLic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addGroup(N5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimpiar)
                            .addComponent(btnBuscar)
                            .addComponent(filtros))
                        .addGap(44, 44, 44)
                        .addComponent(Exit4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(65, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, N5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPadre)
                        .addGap(206, 206, 206))))
        );

        jTabbedPane2.addTab("tab5", N5);

        jPanel1.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 50, 530, 810));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBounds(0, 0, 1576, 868);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_reporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_reporteMouseClicked
        jTabbedPane1.setSelectedIndex(1);
        jTabbedPane2.setSelectedIndex(4);
    }//GEN-LAST:event_bt_reporteMouseClicked

    private void bt_reporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_reporteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_reporteMouseEntered

    private void bt_reporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_reporteMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_reporteMouseExited

    private void bt_importarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_importarMouseClicked
        jTabbedPane1.setSelectedIndex(1);
        jTabbedPane2.setSelectedIndex(1);
    }//GEN-LAST:event_bt_importarMouseClicked

    private void bt_importarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_importarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_importarMouseEntered

    private void bt_importarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_importarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_importarMouseExited

    private void bt_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_buscarMouseClicked
        jTabbedPane1.setSelectedIndex(1);
        jTabbedPane2.setSelectedIndex(2);
        
    }//GEN-LAST:event_bt_buscarMouseClicked

    private void bt_buscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_buscarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_buscarMouseEntered

    private void bt_buscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_buscarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_buscarMouseExited

    private void bt_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregarMouseClicked
        jTabbedPane1.setSelectedIndex(1);
        jTabbedPane2.setSelectedIndex(3);
    }//GEN-LAST:event_bt_agregarMouseClicked

    private void bt_agregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_agregarMouseEntered

    private void bt_agregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_agregarMouseExited

    private void bt_importar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_importar1MouseClicked
        //Codigo para importar
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("Archivos CSV", "csv"));

        // Mostrar el diálogo de abrir archivo
        int returnValue = fileChooser.showOpenDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String filePath = selectedFile.getAbsolutePath();

            // Procesar el archivo seleccionado
            try (CSVReader reader = new CSVReader(new FileReader(filePath))) {
                List<String[]> records = reader.readAll();
                for (String[] record : records) {
                    if (record.length >= 4) {
                        String ruc = record[0].trim();
                        String giroDeActividad = record[1].trim();
                        String areaDeEstablecimiento = record[2].trim();
                        String tipoDeLicencia = record[3].trim();

                        licencias.insertar(ID, ruc, giroDeActividad, areaDeEstablecimiento, tipoDeLicencia);
                        arbolPadre.insertar(ruc, giroDeActividad, areaDeEstablecimiento, tipoDeLicencia);
                        ID++;
                    } else {
                        System.err.println("Registro inválido: " + String.join(",", record));
                    }
                }
            } catch (IOException | CsvException e) {
                e.printStackTrace();
            }

            // Llenar la tabla después de insertar los datos
            llenarTabla();
        } else {
            System.out.println("No se seleccionó ningún archivo.");
        }
        
    }//GEN-LAST:event_bt_importar1MouseClicked

    private void bt_importar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_importar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_importar1MouseEntered

    private void bt_importar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_importar1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_importar1MouseExited

    private void ructxtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ructxtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ructxtbuscarActionPerformed

    private void ructxtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ructxtbuscarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ructxtbuscarKeyReleased

    private void girotxtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girotxtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_girotxtbuscarActionPerformed

    private void girotxtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_girotxtbuscarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_girotxtbuscarKeyReleased

    private void areatxtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areatxtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areatxtbuscarActionPerformed

    private void areatxtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_areatxtbuscarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_areatxtbuscarKeyReleased

    private void lictxtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lictxtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lictxtbuscarActionPerformed

    private void buscarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButton1ActionPerformed
       
        
        //Busqueda de datos en la tabla
        String rucBusc = ructxtbuscar.getText();
        String giroBusc = girotxtbuscar.getText();
        String areaBusc = areatxtbuscar.getText();
        String tipoBusc = lictxtbuscar.getText();

        if(rucBusc.equals(""))
            rucBusc = null ;
        if(giroBusc.equals(""))
            giroBusc = null ;
        if(areaBusc.equals(""))
            areaBusc = null ;
        if(tipoBusc.equals(""))
            tipoBusc = null ;
        
        
        Nodo[] resultados = licencias.buscar(-1, rucBusc , giroBusc, areaBusc, tipoBusc);
        
        if (resultados.length > 0) {
            System.out.println("Nodos encontrados");
            ArbolBinario busc = new ArbolBinario(); 
            for (Nodo nodo : resultados) {
                busc.insertar(nodo.ID, nodo.ruc, nodo.giroActividad, nodo.areaEstablecimiento, nodo.tipoLicencia);
            }
            DefaultTableModel dataModel = new DefaultTableModel(new String[]{"ID", "RUC", "Giro de Actividad", "Área de Establecimiento", "Tipo de Licencia"}, 0);
            busc.llenarTabla(dataModel);
            tblLicencias.setModel(dataModel);
            
        } else {
            System.out.println("No se encontraron nodos que coincidan con los criterios de búsqueda.");
        }
        
        
        
        
    }//GEN-LAST:event_buscarButton1ActionPerformed

    private void Exit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit3ActionPerformed

        txtRucAgregar.setText("");
        txtGiroAgregar.setText("");
        txtAreaAgregar.setText("");
        txtTipoAgregar.setText("");
        
        System.out.println("el id final es: " + ID);
    }//GEN-LAST:event_Exit3ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        licencias.insertar(ID, txtRucAgregar.getText(), txtGiroAgregar.getText(), txtAreaAgregar.getText(), txtTipoAgregar.getText());
        ID++;
        
        llenarTabla();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtRucAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRucAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRucAgregarActionPerformed

    private void txtRUCRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRUCRepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRUCRepActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
          //buscador para crear reportes
          
        String rucRep = txtRUCRep.getText();
        String giroRep = TXTGiroRep.getText();
        String areaBusc = null;
        String tipoBusc = txtTipoLic.getText();

        if(rucRep.equals(""))
            rucRep = null ;
        if(giroRep.equals(""))
            giroRep = null ;
        if(tipoBusc.equals(""))
            tipoBusc = null ;
        
        
        resultados = licencias.buscar(-1, rucRep , giroRep, areaBusc, tipoBusc);
        
        if (resultados.length > 0) {
            
            
        

            
            System.out.println("Nodos encontrados");
            ArbolBinario reporte = new ArbolBinario();
            
            arbolReporte.vaciarArbol();
            for (Nodo nodo : resultados) {
                reporte.insertar(nodo.ID, nodo.ruc, nodo.giroActividad, nodo.areaEstablecimiento, nodo.tipoLicencia);
                
                //Insertar en el miniarbolito de reportes
                
                arbolReporte.insertar(nodo.ruc, nodo.giroActividad, nodo.areaEstablecimiento, nodo.tipoLicencia);
                
                
            }
            DefaultTableModel dataModel = new DefaultTableModel(new String[]{"ID", "RUC", "Giro de Actividad", "Área de Establecimiento", "Tipo de Licencia"}, 0);
            
          

            
            
            reporte.llenarTabla(dataModel);
            tblLicencias.setModel(dataModel);
            
        } else {
            System.out.println("No se encontraron nodos que coincidan con los criterios de búsqueda.");
        }
        

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void Exit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit4ActionPerformed

         pdf obj = new pdf();
        
            Font fontTexto = new Font(Font.HELVETICA, 8, Font.NORMAL, Color.BLACK);
            Paragraph texto1 = new Paragraph("\n", fontTexto);

        
            texto1.add("\n" + arbolReporte.contarEstablecimientos() + "\n");
            texto1.add(arbolReporte.contarGiroActividad() + "\n");
            texto1.add(arbolReporte.contarTipoLicencia() + "\n");
            obj.ReportePDF(texto1,"Reporte Busquedas");
        
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setFileFilter(new FileNameExtensionFilter("Archivos de texto", "txt"));
            int returnValue = fileChooser.showSaveDialog(null);

            if (returnValue == JFileChooser.APPROVE_OPTION) {
                File file = fileChooser.getSelectedFile();
                String filePath = file.getAbsolutePath();
                if (!filePath.endsWith(".txt")) {
                    filePath += ".txt";
                }

                try (FileWriter writer = new FileWriter(filePath)) {
                    
                    for (Nodo nodo : resultados) {
                        writer.write(nodo.ID + "," + nodo.ruc + "," + nodo.giroActividad + "," + nodo.areaEstablecimiento + "," + nodo.tipoLicencia + "\n");
                    }
                    System.out.println("Exportación a archivo de texto completada.");
                } catch (IOException e) {
                    e.printStackTrace();
                }
            } else {
                System.out.println("No se seleccionó ningún archivo para guardar.");
            }
    }//GEN-LAST:event_Exit4ActionPerformed

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        //Agregar nueva Licencia al arbol
        
        
        
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void filtrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrosActionPerformed
        //limpiar filtros del buscador
        DefaultTableModel dataModel = new DefaultTableModel(new String[]{"ID", "RUC", "Giro de Actividad", "Área de Establecimiento", "Tipo de Licencia"}, 0);
        licencias.llenarTabla(dataModel);
        tblLicencias.setModel(dataModel);
        
        
    }//GEN-LAST:event_filtrosActionPerformed

    private void btnPadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPadreActionPerformed
        //Reporte General
        pdf obj = new pdf();
        
        Font fontTexto = new Font(Font.HELVETICA, 8, Font.NORMAL, Color.BLACK);
        Paragraph texto1 = new Paragraph("\n", fontTexto);

        
        texto1.add("\n" + arbolPadre.contarEstablecimientos() + "\n");
        texto1.add(arbolPadre.contarGiroActividad() + "\n");
        texto1.add(arbolPadre.contarTipoLicencia() + "\n");
        obj.ReportePDF(texto1,"Reporte General");
        
        
        
    }//GEN-LAST:event_btnPadreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    public void llenarTabla(){
        DefaultTableModel dataModel = new DefaultTableModel(new String[]{"ID", "RUC", "Giro de Actividad", "Área de Establecimiento", "Tipo de Licencia"}, 0);
        licencias.llenarTabla(dataModel);
        tblLicencias.setModel(dataModel);
    
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit3;
    private javax.swing.JButton Exit4;
    private javax.swing.JPanel N1;
    private javax.swing.JPanel N2;
    private javax.swing.JPanel N3;
    private javax.swing.JPanel N4;
    private javax.swing.JPanel N5;
    private javax.swing.JPanel P1;
    private javax.swing.JPanel P2;
    private javax.swing.JTextField TXTGiroRep;
    private javax.swing.JTextField areatxtbuscar;
    private javax.swing.JLabel bt_agregar;
    private javax.swing.JLabel bt_buscar;
    private javax.swing.JLabel bt_importar;
    private javax.swing.JLabel bt_importar1;
    private javax.swing.JLabel bt_reporte;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnPadre;
    private javax.swing.JButton buscarButton1;
    private javax.swing.JButton filtros;
    private javax.swing.JTextField girotxtbuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField lictxtbuscar;
    private javax.swing.JPanel loginBtn10;
    private javax.swing.JPanel loginBtn4;
    private javax.swing.JPanel loginBtn7;
    private javax.swing.JPanel loginBtn8;
    private javax.swing.JPanel loginBtn9;
    private javax.swing.JTextField ructxtbuscar;
    private javax.swing.JTable tblLicencias;
    private javax.swing.JTextField txtAreaAgregar;
    private javax.swing.JTextField txtGiroAgregar;
    private javax.swing.JTextField txtRUCRep;
    private javax.swing.JTextField txtRucAgregar;
    private javax.swing.JTextField txtTipoAgregar;
    private javax.swing.JTextField txtTipoLic;
    // End of variables declaration//GEN-END:variables
}
